server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy para o backend (opcional, mas ajuda a evitar problemas de CORS no navegador) (I.A)
    # location /api/ {
    #     proxy_pass http://backend:3000/;
    # }
}
